### PR TITLE
"Ten simple actions to make NanoSafety Cluster Research Output more Findable"

### PR DESCRIPTION
**Pull request by egonw**
@thomasexner, I could not get the `bundle` working locally, with the error message `Could not find gem 'github-pages (~> 226)' in cached gems or installed locally.`

So, I hope you can give it a quick check. It now has all the references, and the two images. Should be good to go.

### CODE REVIEW

**Comment by thomasexner** [comment]
@egonw: I made some corrections to the references to make it work. If this is okay with you, I would now merge it into main,

**Comment by egonw** [comment]
> I made some corrections to the references to make it work. If this is okay with you

@thomasexner, where can I see those changes?

**Comment by thomasexner** [comment]
@egonw: Sorry my mistake. I now merged your changes into the ten-simple-actions branch (without addition/) and removed the conflicts I created. Hope everything is fine now.

**Comment by egonw** [comment]
Ah, found it. Thanks! Yes, I'm happy for it to be merged in.

**Pull request merged**
